/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cifrado.vigenere;

import javax.swing.JOptionPane;

/**
 *
 * @author David
 */
public class UI extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    public UI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cifrarBtn = new javax.swing.JButton();
        descifrarBtn = new javax.swing.JButton();
        claveTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        palabraTxt = new javax.swing.JTextField();
        resultadoTtx = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));

        cifrarBtn.setText("Cifrar");
        cifrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cifrarBtnActionPerformed(evt);
            }
        });

        descifrarBtn.setText("Descifrar");
        descifrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descifrarBtnActionPerformed(evt);
            }
        });

        claveTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claveTxtActionPerformed(evt);
            }
        });

        jLabel1.setText("Clave:");

        palabraTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                palabraTxtActionPerformed(evt);
            }
        });

        resultadoTtx.setEditable(false);
        resultadoTtx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoTtxActionPerformed(evt);
            }
        });

        jLabel2.setText("Palabra:");

        jLabel3.setText("Resultado:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cifrarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(descifrarBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(claveTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(palabraTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                .addComponent(resultadoTtx, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(claveTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(palabraTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultadoTtx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cifrarBtn)
                    .addComponent(descifrarBtn))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String palabra, clave;
    Datos datos = new Datos();
    private void cifrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cifrarBtnActionPerformed
        boolean error = false;
        if (datos.isCifrado()) {
            JOptionPane.showMessageDialog(null, "La palabra ya está cifrada");
        } else {
            datos.setCifrado(true);
            palabra = palabraTxt.getText();
            clave = claveTxt.getText().toLowerCase();
            for (int i = 0; i < clave.length(); i++) {
                if (clave.length() > palabra.length() || datos.abc.indexOf(clave.charAt(i)) < 0) {
                    JOptionPane.showMessageDialog(null, "Error con la clave,revise que no contenga caracteres especiales ni sea más larga que la frase a cifrar");
                    error = true;
                    break;
                }
            }
            if (error == false) {
                resultadoTtx.setText(datos.Cifrar(clave, palabra));
            }
        }

    }//GEN-LAST:event_cifrarBtnActionPerformed

    private void claveTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claveTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_claveTxtActionPerformed

    private void palabraTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_palabraTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_palabraTxtActionPerformed

    private void resultadoTtxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoTtxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultadoTtxActionPerformed

    private void descifrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descifrarBtnActionPerformed
        if (datos.isCifrado()) {
            palabra = resultadoTtx.getText();
            resultadoTtx.setText(datos.Descifrar(clave, palabra));
            datos.setCifrado(false);
        } else {
            JOptionPane.showMessageDialog(null, "La palabra ya está descifrada");
        }
    }//GEN-LAST:event_descifrarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cifrarBtn;
    private javax.swing.JTextField claveTxt;
    private javax.swing.JButton descifrarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField palabraTxt;
    private javax.swing.JTextField resultadoTtx;
    // End of variables declaration//GEN-END:variables
}
